CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers_db 
(
	id INT NOT NULL AUTO INCREMENT,
	burger_name VARCHAR(255) BOOLEAN,
	devoured BOOLEAN DEFAULT FALSE,
	time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	date DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

 